"""平台领域模型、协议与注册表（无 I/O）。"""
from agent_platform.core.domain.backtest_strategy import BacktestStrategy
from agent_platform.core.domain.data_providers import (
    DataProviderRegistry,
    DataProviderSpec,
)
from agent_platform.core.domain.models import (
    BacktestResult,
    DailyMarketEvent,
    EvolutionNote,
    Features,
    FeedbackRequest,
    GenerateRequest,
    GenerateResponse,
    HighlightedSector,
    LlmBackend,
    LlmError,
    LlmTokens,
    MarketSnapshot,
    MetricsSnapshot,
    Mode,
    NamedIndexRef,
    Provider,
    Recap,
    RecapDaily,
    RecapDailySection,
    RecapStrategy,
)

__all__ = [
    "BacktestStrategy",
    "DataProviderRegistry",
    "DataProviderSpec",
    "BacktestResult",
    "DailyMarketEvent",
    "EvolutionNote",
    "Features",
    "FeedbackRequest",
    "GenerateRequest",
    "GenerateResponse",
    "HighlightedSector",
    "LlmBackend",
    "LlmError",
    "LlmTokens",
    "MarketSnapshot",
    "MetricsSnapshot",
    "Mode",
    "NamedIndexRef",
    "Provider",
    "Recap",
    "RecapDaily",
    "RecapDailySection",
    "RecapStrategy",
]
